languageCode = "en-us"
baseURL = "https://czaplewski.be/"
title = "Valérie Czaplewski"
theme = "split"
disableKinds = ["section", "taxonomy", "RSS"]
copyright = "© Valérie Czaplewski. VAT# BE1005244553"
enableGitInfo = true
enableRobotsTXT = true
enableEmoji = true
author = "Valérie Czaplewski"
summaryLength = 50

[minify]
minifyOutput = true

[privacy.x]
disable = false
enableDNT = true
simple = false

[params]
author = "Valérie Czaplewski"
description = "UX designer focused on what matters most: real people. I combine user research with thoughtful design to challenge assumptions and create meaningful experiences — including in conversational UX."

[params.visual]
[params.visual.image]
enable = true
file = "images/profilepic.jpg"
position = "center center"

[[params.links]]
[params.links.list1]
heading = "Connect"
[[params.links.list1.link]]
text = "LinkedIn"
url = "https://www.linkedin.com/in/valeriecz/"
new_tab = true
[[params.links.list1.link]]
text = "Email"
url = "mailto:valerie@czaplewski.be"